

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  maven_compile_test_package: 
    runs-on: self-hosted 
    steps: 
    - uses: actions/checkout@v3
    - run: mvn -version
    - name: Build with Maven 
      run: mvn compile
    - run: mvn test
    - run: mvn package
