

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  maven_compile_test_package: 
    runs-on: self-hosted 
    steps: 
    - uses: actions/checkout@v3
    - run: mvn -version
    - name: Build with Maven 
      run: mvn compile
    - run: mvn test
    - run: mvn package
  sonarqube_publish_report:
    runs-on: self-hosted 
    needs: maven_compile_test_package
    steps:
     - name: SonarQube Scan 
       uses: sonarsource/sonarqube-scan-action@master 
       env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
  trivy_fs_scan:
    runs-on: self-hosted 
    needs: sonarqube_publish_report
    steps:
    - run: trivy fs --format table -o fs.html .
    - name: Upload fs.html as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fs-report
        path: fs.html
  packaging:
    runs-on: self-hosted 
    needs: trivy_fs_scan
    steps:
    - run: mvn clean package
    - uses: actions/upload-artifact@v4
      with:
        name: artifactjar
        path: target/*.jar
    
